version: 0.2
#run-as: root
proxy:
  logs: yes
phases:
  pre_build:
#    run-as: root
    on-failure: ABORT
    commands:
      - echo Logging into ECR...
      - docker --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 059407755516.dkr.ecr.ap-south-1.amazonaws.com
  build:
#    run-as: root
    on-failure: ABORT
    commands:
      - echo Entered the build phase...
      - echo Building Flutter Web App Started on `date`
      - docker build -t iqmockstudent-fe-dev .
      - docker tag iqmockstudent-fe-dev:latest 059407755516.dkr.ecr.ap-south-1.amazonaws.com/iqmockstudent-fe-dev:latest
  post_build:
#    run-as: root
    on-failure: ABORT
    commands:
      - echo Entered the post_build phase....
      - echo Pushing iqmockstudent-fe-dev Docker Image to ECR
      - docker push 059407755516.dkr.ecr.ap-south-1.amazonaws.com/iqmockstudent-fe-dev:latest
~                                                                                                                                                             
~                                                                                                                                                             
~                                                                                                                                                             
~                                                                                                                                                             
~                                                 
