  [context.production]
  [context.production.environment]
    REACT_APP_BASE_URL= ""
   
   

[context.staging]
  [context.staging.environment]
   REACT_APP_BASE_URL= "https://tlwojqenmffmbuf6fwdxxpa6ky0tgcos.lambda-url.ap-south-1.on.aws"

   
 

[context.dev]
  [context.dev.environment]
    REACT_APP_BASE_URL= "https://tlwojqenmffmbuf6fwdxxpa6ky0tgcos.lambda-url.ap-south-1.on.aws"
   
    
