  [context.production]
  [context.production.environment]
    REACT_APP_BASE_URL= ""
   
   

[context.staging]
  [context.staging.environment]
   REACT_APP_BASE_URL= "https://us-central1-mock-test-45864.cloudfunctions.net/app                                                                                                                                                                                                                                                                    "
   
 

[context.dev]
  [context.dev.environment]
    REACT_APP_BASE_URL= "https://us-central1-mock-test-45864.cloudfunctions.net/app"
   
    
