  [context.production]
  [context.production.environment]
    REACT_APP_BASE_URL= "http://mockapi.iquanta.in"
   
   

[context.staging]
  [context.staging.environment]
   REACT_APP_BASE_URL= "http://mockapi.iquanta.in"
   
 

[context.dev]
  [context.dev.environment]
    REACT_APP_BASE_URL= "http://mockapi.iquanta.in"
   
    
